version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
    - "9090:9090"
    volumes:
    - prometheus_data:/prometheus
    - "./prometheus.yml:/var/lib/prometheus/prometheus.yml"
  node-exporter:
    image: prom/node-exporter:latest
    ports:
    - "9100:9100"
  grafana:
    image: grafana/grafana:latest
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
    - prometheus
    ports:
    - "3001:3001"
    volumes:
    - grafana_data:/var/lib/grafana
  app:
    build: "."
    restart: "always"
    ports:
    - ${APP_PORT:-3000}:3000
    env_file:
    - ".env"
    depends_on:
    - "db_test"
    volumes:
    - ".:/go/src/github.com/oysterprotocol/brokernode"
    - "./data/badger/prod:/var/lib/badger/prod"
    - "./data/badger/test:/var/lib/badger/test"
    working_dir: "/go/src/github.com/oysterprotocol/brokernode"
    command: >
      bash -c "
        echo waiting for db_test...;
        while ! nc -z db_test 3306;
        do
          sleep 0.5;
        done;

        echo ${DEBUG}
        if [ -z ${DEBUG} ]; then
          echo \"Starting Buffalo PROD mode\";
          # buffalo db migrate;
          buffalo build -o ./bin/brokernode && chmod +x ./bin/brokernode;
          ./bin/brokernode;

        else
          echo \"Starting Buffalo DEV mode\";
          # buffalo db migrate;
          buffalo dev;
        fi
      "

  # TODO: Figure out a better way to handle multiple envs
  db_test:
    image: "mariadb:10.3"
    restart: "always"
    environment:
    - MYSQL_DATABASE=brokernode_test
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASSWORD=secret
    # - MYSQL_DATABASE=${DB_NAME_TEST:-test}
    # - MYSQL_ROOT_USER=${DB_USER_TEST:-root}
    # - MYSQL_ROOT_PASSWORD=${DB_USER_TEST:-secret}
    volumes:
    - "./data/mariadb/test:/var/lib/mariadb"
    - "./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"